<a href="https://colab.research.google.com/github/arulmr0/deeplearningpytorch/blob/main/TensorinPytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np


# Lists

In [ ]:
mylist=[[1,2,3,4,5,6],[7,8,9,10,11]]
mylist

[[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11]]

# numpy

In [ ]:
np1=np.random.rand(4)
np1


array([0.03370775, 0.38507918, 0.3771575 , 0.62692026])

In [ ]:
np1.dtype

dtype('float64')

TENSORS

In [ ]:
tensor_2d=torch.randn(5,2)
tensor_2d

tensor([[-0.4898, -0.7371],
        [-0.4068,  0.0708],
        [ 0.4608, -0.9098],
        [ 1.1954, -0.4616],
        [-1.3815, -1.4288]])

In [ ]:
tensor_3d=torch.zeros(3,3,6)
tensor_3d

tensor([[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]])

In [ ]:
mytensor=torch.tensor(np1)
mytensor

tensor([0.0337, 0.3851, 0.3772, 0.6269], dtype=torch.float64)

# Tensoroperations

In [ ]:
my_torch=torch.arange(20)
my_torch

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [ ]:
my_torch=my_torch.reshape(5,4)
my_torch

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [ ]:
my_torch2=torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch2=my_torch2.reshape(-1,5)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [37]:
my_torch3=torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Reshape and view

In [29]:
mytorch4=my_torch3.reshape(2,5)
mytorch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [32]:
mytorch4[1]=4567
mytorch4

tensor([[   0,    1,    2,    3,    4],
        [4567, 4567, 4567, 4567, 4567]])

In [40]:
mytorch5=my_torch3
mytorch5[8]

tensor(8)

In [41]:
mytorch6=mytorch5.reshape(5,2)
mytorch6

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

slice

In [45]:
mytorch7=mytorch6[:,0:]
mytorch7

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [48]:
mytorch7[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])