<a href="https://colab.research.google.com/github/arulmr0/deeplearningpytorch/blob/main/TensorinPytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import torch
import numpy as np


# Lists

In [3]:
mylist=[[1,2,3,4,5,6],[7,8,9,10,11]]
mylist

[[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11]]

# numpy

In [9]:
np1=np.random.rand(4)
np1


array([0.03370775, 0.38507918, 0.3771575 , 0.62692026])

In [8]:
np1.dtype

dtype('float64')

TENSORS

In [13]:
tensor_2d=torch.randn(5,2)
tensor_2d

tensor([[-0.4898, -0.7371],
        [-0.4068,  0.0708],
        [ 0.4608, -0.9098],
        [ 1.1954, -0.4616],
        [-1.3815, -1.4288]])

In [14]:
tensor_3d=torch.zeros(3,3,6)
tensor_3d

tensor([[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]])

In [15]:
mytensor=torch.tensor(np1)
mytensor

tensor([0.0337, 0.3851, 0.3772, 0.6269], dtype=torch.float64)

# Tensoroperations

In [18]:
my_torch=torch.arange(20)
my_torch

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [19]:
my_torch=my_torch.reshape(5,4)
my_torch

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])